database:
  # Number of max Open connections to SQLite DB
  maxOpenConns: 5
  # Number of max Idle connections to SQLite DB
  maxIdleConns: 5
  # Number of minutes connection will live
  connMaxLifetime: 30
  # Path to SQLite DB
  dbFile: "/tmp/db-test/harvestor.db"

walker:
  # File walker root path for media files
  EntryPointPath: "/tmp/data-test"
  # FilesOfInterest: "jpg, png"
  FilesOfInterest: "yml"

httpclient:
  timeOut: 300
  maxIdleConnections: 10 
  RetryMax: 2 # how many times to retry
  RetryWaitMin: 3 # how many seconds to wait for retry
  baseApiUrl: "http://localhost:8081"
  upload: "/api/v1/file"
  uploadGroup: "cnc"
  meta: "/api/v1/metadata"
  managedmeta: "/api/v1/managed-attribute-map"
  derivative: "/api/v1/derivative"

keycloak:
  # !!! Important !!!
  # Please read all comments in httpclient/keycloak.go before running
  host: "http://keycloak:8080"
  adminClientID: "objectstore"
  userName: "cnc-cm"
  userPassword: "cnc-cm"
  grantType: "password"
  realmName: "dina"
  newTokenBefore: 15 # 15 seconds before Access token expires need to get new one 
  # !!! Important !!!
  # if you set to true, lots of sensitive information will be shown on the screen
  # !!! Please do not set to true if you are demoing !!!
  debug: false
  # !!! Important !!!
  # set to `false` from current `true` only if you are running against dev
  # otherwise it will always fail with 401 - Status Unauthorized
  enabled: true

logger:
  level: "Info"
  path: "/tmp/log-test"
  file: "harvestor.log"

app:
  release: "0.01"
  name: "harvestor"
  # Bio cluster or PC
  env: "cluster"
  # EXIF does not provide timezone information so the following timezone will be used for the objects uploaded by the harvestor
  objectTimezone: "America/New_York"
