database:
  # Number of max Open connections to SQLite DB
  maxOpenConns: 5
  # Number of max Idle connections to SQLite DB
  maxIdleConns: 5
  # Number of minutes connection will live
  connMaxLifetime: 30
  # Path to SQLite DB
  dbFile: "/tmp/db-test/harvestor.db"

walker:
  # File walker root path for media files
  EntryPointPath: "/tmp/data-test"
  FilesOfInterest: "jpg, png"

httpclient:
  timeOut: 300
  maxIdleConnections: 10 
  RetryMax: 2 # how many times to retry
  RetryWaitMin: 3 # how many seconds to wait for retry
  baseApiUrl: "http://localhost:8081"
  upload: "/api/v1/file/dev-group"
  meta: "/api/v1/metadata"

logger:
  level: "Info"
  path: "/tmp"
  file: "harvestor.log"

app:
  release: "0.01"
  name: "harvestor"
  env: "dev"
