name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Install dependencies
        working-directory: ./harvestor
        run: |
          go mod tidy

      - name: setup coverprofile
        working-directory: ./harvestor
        run: |
          go test ./... -v -cover




